const GET_INGREDIENTS = "GET_INGREDIENTS";
const GET_INGREDIENTS_SUCCESS = "GET_INGREDIENTS_SUCCESS";
const GET_INGREDIENTS_FAILED = "GET_INGREDIENTS_FAILED";

const OPEN_INGREDIENT = "OPEN_INGREDIENT";
const CLOSE_INGREDIENT = "CLOSE_INGREDIENT";

const CREATE_ORDER = "CREATE_ORDER";
const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
const CREATE_ORDER_FAILED = "CREATE_ORDER_FAILED";


export { GET_INGREDIENTS, GET_INGREDIENTS_SUCCESS, GET_INGREDIENTS_FAILED, OPEN_INGREDIENT, CLOSE_INGREDIENT, 
    CREATE_ORDER, CREATE_ORDER_SUCCESS, CREATE_ORDER_FAILED }; 
