export const REGISTER_USER: "REGISTER_USER" = "REGISTER_USER";
export const REGISTER_USER_SUCCESS: "REGISTER_USER_SUCCESS" = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILED: "REGISTER_USER_FAILED" = "REGISTER_USER_FAILED";
export const REGISTER_USER_RESET_DATA: "REGISTER_USER_RESET_DATA" = "REGISTER_USER_RESET_DATA";

export const LOGIN_USER: "LOGIN_USER" = "LOGIN_USER";
export const LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS" = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILED: "LOGIN_USER_FAILED" = "LOGIN_USER_FAILED";
export const LOGIN_USER_RESET_DATA: "LOGIN_USER_RESET_DATA" = "LOGIN_USER_RESET_DATA";

export const FORGOT_PASSWORD: "FORGOT_PASSWORD" = "FORGOT_PASSWORD";
export const FORGOT_PASSWORD_SUCCESS: "FORGOT_PASSWORD_SUCCESS" = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAILED: "FORGOT_PASSWORD_FAILED" = "FORGOT_PASSWORD_FAILED";
export const FORGOT_PASSWORD_RESET_DATA: "FORGOT_PASSWORD_RESET_DATA" = "FORGOT_PASSWORD_RESET_DATA";

export const RESET_PASSWORD: "RESET_PASSWORD" = "RESET_PASSWORD";
export const RESET_PASSWORD_SUCCESS: "RESET_PASSWORD_SUCCESS" = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAILED: "RESET_PASSWORD_FAILED" = "RESET_PASSWORD_FAILED";
export const RESET_PASSWORD_RESET_DATA: "RESET_PASSWORD_RESET_DATA" = "RESET_PASSWORD_RESET_DATA";

export const GET_USER: "GET_USER" = "GET_USER";
export const GET_USER_SUCCESS : "GET_USER_SUCCESS" = "GET_USER_SUCCESS";
export const GET_USER_FAILED: "GET_USER_FAILED" = "GET_USER_FAILED";
export const GET_USER_RESET_DATA:"GET_USER_RESET_DATA" = "GET_USER_RESET_DATA";

export const UPDATE_USER: "UPDATE_USER" = "UPDATE_USER";
export const UPDATE_USER_SUCCESS : "UPDATE_USER_SUCCESS" = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILED : "UPDATE_USER_FAILED" = "UPDATE_USER_FAILED";
export const UPDATE_USER_RESET_DATA : "UPDATE_USER_RESET_DATA" = "UPDATE_USER_RESET_DATA";

export const LOGOUT_USER: "LOGOUT_USER" = "LOGOUT_USER";
export const LOGOUT_USER_SUCCESS: "LOGOUT_USER_SUCCESS" = "LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_FAILED: "LOGOUT_USER_FAILED" = "LOGOUT_USER_FAILED";
export const LOGOUT_USER_RESET_DATA: "LOGOUT_USER_RESET_DATA" = "LOGOUT_USER_RESET_DATA";

export const GET_INGREDIENTS: "GET_INGREDIENTS" = "GET_INGREDIENTS";
export const GET_INGREDIENTS_SUCCESS: "GET_INGREDIENTS_SUCCESS" = "GET_INGREDIENTS_SUCCESS";
export const GET_INGREDIENTS_FAILED: "GET_INGREDIENTS_FAILED" = "GET_INGREDIENTS_FAILED";

export const ADD_INGREDIENT_DETAILS: "ADD_INGREDIENT_DETAILS" = "ADD_INGREDIENT_DETAILS";
export const REMOVE_INGREDIENT_DETAILS: "REMOVE_INGREDIENT_DETAILS" = "REMOVE_INGREDIENT_DETAILS";

export const ADD_INGREDIENT: "ADD_INGREDIENT" = "ADD_INGREDIENT";
export const DELETE_INGREDIENT: "DELETE_INGREDIENT" = "DELETE_INGREDIENT";
export const MOVE_INGREDIENT: "MOVE_INGREDIENT" = "MOVE_INGREDIENT";
export const CLEAR_CONSTRUCTOR: "CLEAR_CONSTRUCTOR" = "CLEAR_CONSTRUCTOR";

export const CREATE_ORDER: "CREATE_ORDER" = "CREATE_ORDER";
export const CREATE_ORDER_SUCCESS: "CREATE_ORDER_SUCCESS" = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAILED : "CREATE_ORDER_FAILED"= "CREATE_ORDER_FAILED";
export const REMOVE_ORDER_NUMBER: "REMOVE_ORDER_NUMBER" = "REMOVE_ORDER_NUMBER";

export const GET_ORDER: "GET_ORDER" = "GET_ORDER";
export const GET_ORDER_SUCCESS: "GET_ORDER_SUCCESS" = "GET_ORDER_SUCCESS";
export const GET_ORDER_FAILED: "GET_ORDER_FAILED" = "GET_ORDER_FAILED";

export const WS_FEED_CONNECTION_START: "WS_FEED_CONNECTION_START" = "WS_FEED_CONNECTION_START";
export const WS_FEED_CONNECTION_SUCCESS: "WS_FEED_CONNECTION_SUCCESS" = "WS_FEED_CONNECTION_SUCCESS";
export const WS_FEED_CONNECTION_ERROR: "WS_FEED_CONNECTION_ERROR" = "WS_FEED_CONNECTION_ERROR";
export const WS_FEED_CONNECTION_CLOSED: "WS_FEED_CONNECTION_CLOSED" = "WS_FEED_CONNECTION_CLOSED";
export const WS_FEED_CONNECTION_FINISH: "WS_FEED_CONNECTION_FINISH" = "WS_FEED_CONNECTION_FINISH";
export const WS_FEED_GET_MESSAGE: "WS_FEED_GET_MESSAGE" = "WS_FEED_GET_MESSAGE";
export const WS_FEED_SEND_MESSAGE:"WS_FEED_SEND_MESSAGE" = "WS_FEED_SEND_MESSAGE";

export const WS_HISTORY_CONNECTION_START: "WS_HISTORY_CONNECTION_START" = "WS_HISTORY_CONNECTION_START";
export const WS_HISTORY_CONNECTION_SUCCESS: "WS_HISTORY_CONNECTION_SUCCESS" = "WS_HISTORY_CONNECTION_SUCCESS";
export const WS_HISTORY_CONNECTION_ERROR: "WS_HISTORY_CONNECTION_ERROR" = "WS_HISTORY_CONNECTION_ERROR";
export const WS_HISTORY_CONNECTION_CLOSED: "WS_HISTORY_CONNECTION_CLOSED" = "WS_HISTORY_CONNECTION_CLOSED";
export const WS_HISTORY_CONNECTION_FINISH: "WS_HISTORY_CONNECTION_FINISH" = "WS_HISTORY_CONNECTION_FINISH";
export const WS_HISTORY_GET_MESSAGE: "WS_HISTORY_GET_MESSAGE" = "WS_HISTORY_GET_MESSAGE";
export const WS_HISTORY_SEND_MESSAGE: "WS_HISTORY_SEND_MESSAGE" = "WS_HISTORY_SEND_MESSAGE";

export const UPDATE_TOKEN: "UPDATE_TOKEN" = "UPDATE_TOKEN";
export const UPDATE_TOKEN_SUCCESS: "UPDATE_TOKEN_SUCCESS" = "UPDATE_TOKEN_SUCCESS";
export const UPDATE_TOKEN_FAILED: "UPDATE_TOKEN_FAILED" = "UPDATE_TOKEN_FAILED";

export const INVALID_OR_MISSING_TOKEN: "Invalid or missing token" = "Invalid or missing token";