const GET_INGREDIENTS = "GET_INGREDIENTS";
const GET_INGREDIENTS_SUCCESS = "GET_INGREDIENTS_SUCCESS";
const GET_INGREDIENTS_FAILED = "GET_INGREDIENTS_FAILED";

const OPEN_INGREDIENT = "OPEN_INGREDIENT";
const CLOSE_INGREDIENT = "CLOSE_INGREDIENT";

const ADD_INGREDIENT = "ADD_INGREDIENT";
const DELETE_INGREDIENT = "DELETE_INGREDIENT";

const CREATE_ORDER = "CREATE_ORDER";
const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
const CREATE_ORDER_FAILED = "CREATE_ORDER_FAILED";

const ADD_PRICE = "ADD_PRICE";
const DELETE_PRICE = "DELETE_PRICE";

export { GET_INGREDIENTS, GET_INGREDIENTS_SUCCESS, GET_INGREDIENTS_FAILED, OPEN_INGREDIENT, CLOSE_INGREDIENT, 
    ADD_INGREDIENT, DELETE_INGREDIENT, CREATE_ORDER, CREATE_ORDER_SUCCESS, CREATE_ORDER_FAILED, ADD_PRICE, DELETE_PRICE };