const CREATE_ORDER = "CREATE_ORDER";
const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
const CREATE_ORDER_FAILED = "CREATE_ORDER_FAILED";

export { CREATE_ORDER, CREATE_ORDER_SUCCESS, CREATE_ORDER_FAILED }; 