export const REGISTER_USER: "REGISTER_USER" = "REGISTER_USER";
export const REGISTER_USER_SUCCESS: "REGISTER_USER_SUCCESS" = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILED: "REGISTER_USER_FAILED" = "REGISTER_USER_FAILED";
export const REGISTER_USER_RESET_DATA: "REGISTER_USER_RESET_DATA" = "REGISTER_USER_RESET_DATA";

export const LOGIN_USER: "LOGIN_USER" = "LOGIN_USER";
export const LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS" = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILED: "LOGIN_USER_FAILED" = "LOGIN_USER_FAILED";
export const LOGIN_USER_RESET_DATA: "LOGIN_USER_RESET_DATA" = "LOGIN_USER_RESET_DATA";

export const FORGOT_PASSWORD: "FORGOT_PASSWORD" = "FORGOT_PASSWORD";
export const FORGOT_PASSWORD_SUCCESS: "FORGOT_PASSWORD_SUCCESS" = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAILED: "FORGOT_PASSWORD_FAILED" = "FORGOT_PASSWORD_FAILED";
export const FORGOT_PASSWORD_RESET_DATA: "FORGOT_PASSWORD_RESET_DATA" = "FORGOT_PASSWORD_RESET_DATA";

export const RESET_PASSWORD: "RESET_PASSWORD" = "RESET_PASSWORD";
export const RESET_PASSWORD_SUCCESS: "RESET_PASSWORD_SUCCESS" = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAILED: "RESET_PASSWORD_FAILED" = "RESET_PASSWORD_FAILED";
export const RESET_PASSWORD_RESET_DATA: "RESET_PASSWORD_RESET_DATA" = "RESET_PASSWORD_RESET_DATA";

export const GET_USER: "GET_USER" = "GET_USER";
export const GET_USER_SUCCESS : "GET_USER_SUCCESS" = "GET_USER_SUCCESS";
export const GET_USER_FAILED: "GET_USER_FAILED" = "GET_USER_FAILED";
export const GET_USER_RESET_DATA:"GET_USER_RESET_DATA" = "GET_USER_RESET_DATA";

export const UPDATE_USER: "UPDATE_USER" = "UPDATE_USER";
export const UPDATE_USER_SUCCESS : "UPDATE_USER_SUCCESS" = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILED : "UPDATE_USER_FAILED" = "UPDATE_USER_FAILED";
export const UPDATE_USER_RESET_DATA : "UPDATE_USER_RESET_DATA" = "UPDATE_USER_RESET_DATA";

export const LOGOUT_USER: "LOGOUT_USER" = "LOGOUT_USER";
export const LOGOUT_USER_SUCCESS: "LOGOUT_USER_SUCCESS" = "LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_FAILED: "LOGOUT_USER_FAILED" = "LOGOUT_USER_FAILED";
export const LOGOUT_USER_RESET_DATA: "LOGOUT_USER_RESET_DATA" = "LOGOUT_USER_RESET_DATA";