const urlBase = "https://norma.nomoreparties.space/api/";

const GET_INGREDIENTS = "GET_INGREDIENTS";
const GET_INGREDIENTS_SUCCESS = "GET_INGREDIENTS_SUCCESS";
const GET_INGREDIENTS_FAILED = "GET_INGREDIENTS_FAILED";

const ADD_INGREDIENT_DETAILS = "ADD_INGREDIENT_DETAILS";
const REMOVE_INGREDIENT_DETAILS = "REMOVE_INGREDIENT_DETAILS";

const ADD_INGREDIENT = "ADD_INGREDIENT";
const DELETE_INGREDIENT = "DELETE_INGREDIENT";
const MOVE_INGREDIENT = "MOVE_INGREDIENT";
const CLEAR_CONSTRUCTOR = "CLEAR_CONSTRUCTOR";

const CREATE_ORDER = "CREATE_ORDER";
const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
const CREATE_ORDER_FAILED = "CREATE_ORDER_FAILED";
const REMOVE_ORDER_NUMBER = "REMOVE_ORDER_NUMBER";

const ADD_PRICE = "ADD_PRICE";
const DELETE_PRICE = "DELETE_PRICE";

export { urlBase, GET_INGREDIENTS, GET_INGREDIENTS_SUCCESS, GET_INGREDIENTS_FAILED, ADD_INGREDIENT_DETAILS, REMOVE_INGREDIENT_DETAILS, 
    ADD_INGREDIENT, DELETE_INGREDIENT, MOVE_INGREDIENT, CLEAR_CONSTRUCTOR, CREATE_ORDER, CREATE_ORDER_SUCCESS, 
    CREATE_ORDER_FAILED, REMOVE_ORDER_NUMBER, ADD_PRICE, DELETE_PRICE };